Implement Class Mastery page
CPSECapstone/webrew pull request #33
Opened 2021-05-12 21:02 UTC by nguyen-darianhuy

Summary
---
-[x] Implemented Class Mastery design and filled it with mock data
-[ ] Connect it to backend
-[ ] Provide a clickable link to it on another page

2021-05-12 22:46 UTC, mattcuento requested changes
Create index files to avoid repitition of path names in import statements, good other than that

2021-05-12 22:46 UTC, mattcuento commented on src/Components/Content/Content.tsx
>  import SingleStudentOverview from '../SingleStudentOverview/SingleStudentOverview';
Create index files within each Component folder to avoid repetition of path names

2021-05-12 22:46 UTC, mattcuento commented on src/Components/Content/Content.tsx
>  import SingleStudentOverview from '../SingleStudentOverview/SingleStudentOverview';
Ditto for the components below

2021-05-12 22:46 UTC, mattcuento commented on src/Screens/ClassMastery/ClassMastery.tsx
> +const MOCK_DATA = [
Abstract mock data to the mock folder

2021-05-12 22:47 UTC, rmfay1 reviewed
complete matt's requested changes

2021-05-14 03:59 UTC, nguyen-darianhuy commented
Addressed changes

2021-05-19 22:37 UTC, merged